config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'

  root 'top#index'
  resources :topics do
    resources :comments
  end
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :users, only: [:index, :show]
  resources :relationships, only: [:create, :destroy]
  resources :conversations do
    resources :messages
  end
  if Rails.env.development?
   mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :topic
  has_many :notifications, dependent: :destroy
  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    # ログインユーザーに紐付けてインスタンス生成するためbuildメソッドを使用します。
    @comment = current_user.comments.build(comment_params)
    @topic = @comment.topic
    @notification = @comment.notifications.build(user_id: @topic.user.id ) if current_user.comment_user?(@topic)

    # クライアント要求に応じてフォーマットを変更
    respond_to do |format|
      if @comment.save
        format.html { redirect_to topic_path(@topic), notice: 'コメントを投稿しました。' }
        format.json { render :show, status: :created, location: @comment }
        # JS形式でレスポンスを返します。
        format.js { render :index }
        unless @comment.topic.user_id == current_user.id
          Pusher.trigger("user_#{@comment.topic.user_id}_channel", 'comment_created', {
            message: 'あなたの作成したブログにコメントが付きました'
          })
          Pusher.trigger("user_#{@comment.topic.user_id}_channel", 'notification_created', {
            unread_counts: Notification.where(user_id: @comment.topic.user.id, read: false).count
          })
        end
      else
        format.html { render :new, alert:"未入力の項目があります" }
        format.json { render json: @comment.errors, status: :unprocessable_entity}
      end
    end
  end
  def destroy
      @comment = Comment.find(params[:id])
    # クライアント要求に応じてフォーマットを変更
      @comment.destroy
      render :index
  end
  private
  # ストロングパラメーター
  def comment_params
    params.require(:comment).permit(:topic_id, :content)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([topic,comment], remote: true) do |f| %>
  <%= f.error_messages! %>
  <%= f.hidden_field :topic_id %>
  <div class="field">
    <%= f.text_area :content, placeholder: "コメントを入力して下さい", class: "form-control" %>
  </div>
  <div class="">
    <%= f.submit class: "btn button-large" %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<% comments.each do |comment| %>
  <% unless comment.id.nil? %>
    <div class="comments">
    <p><%= comment.user.name %>さんがコメントしました。</p>
    <p><%= comment.content %></p>
    <% if current_user.id == comment.user.id %>
      <p class="right">
        <%= link_to '', topic_comment_path(topic, comment), class: "fa fa-trash-o fa-lg", method: :delete, remote: true, data: { confirm: '本当に削除していいですか？' } %>
      </p>
    <% end %>
    </div>
  <% end %>
<% end %>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments:@comment.topic.comments, topic: @comment.topic }) %>")
$(':text').val('')