config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'

  root 'top#index'
  resources :topics do
    resources :comments
  end
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :users, only: [:index, :show]
  resources :relationships, only: [:create, :destroy]
  resources :conversations do
    resources :messages
  end
  if Rails.env.development?
   mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  def index
    redirect_to root_path
  end

  def new
    if params[:back]
      @topic = Topic.new(topics_params)
    else
      @topic = Topic.new
    end
  end

  def create
    @topic = Topic.new(topics_params)
    @topic.user_id = current_user.id
    if @topic.save
      redirect_to root_path, notice:"投稿されました"
    else
      redirect_to root_path, alert:"未入力の項目があります"
      @topic = Topic.new(topics_params)
    end
  end

  def edit
  end

  def update
    @topic.update(topics_params)
    redirect_to topics_path, notice:"投稿を更新しました"
  end

  def destroy
    @topic.destroy
    redirect_to root_path, alert:"投稿を削除しました"
  end

  def show
    @comment = @topic.comments.build
    @comments = @topic.comments
  end

  private
    def topics_params
      params.require(:topic).permit(:title,:content)
    end
    def set_topic
      @topic = Topic.find(params[:id])
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <div class="topcic-title-box">
    <%= f.error_messages! %>
    <%= f.label :タイトル %>
    <%= f.text_field :title, class: "form-control",required:true %>
  </div>
  <div class="topcic-content-box">
    <%= f.label :内容 %>
    <%= f.text_area :content, class: "form-control", placeholder: "今なにしてる？",required:true %>
  </div>
  <div class="topcic-submit-box" id="topEditBtnDiv" style="display: none;">
    <%= f.submit '投稿する',id:"topEditBtn"%>
  </div>
<% end %>

app/views/topics/edit.html.erb
<div class="edit-content">
  <h2 class="title">投稿の編集</h2>
  <%= render 'form' %>
  <%= link_to "もどる", :back %>
</div>

app/views/topics/index.html.erb
<% @topics.each do |topic| %>
  <%= topic.title %>
  <p>投稿者：<%= topic.user.name %></p>
  <%= topic.content %>
  <%= link_to "コメントする", topic_path(topic) %>
  <%= link_to "編集", edit_topic_path(topic.id) %>
  <%= link_to "削除", topic_path(topic.id), method: :delete, data: { confirm: '本当に削除しますか？'}%>
<% end %>
<%= link_to "新規投稿", new_topic_path %>

app/views/topics/new.html.erb
<%= render 'form' %>

app/views/topics/show.html.erb
<article class="article">
  <h2 class="title">投稿記事</h2>
  <p><%= @topic.user.name %></p>
  <p><%= @topic.title %></p>
  <p><%= @topic.content %></p>
</article>
<h2 class="title">コメント一覧</h2>
  <div id="comments_area">
    <%= render partial: 'comments/index', locals: { comments: @comments, topic: @topic } %>
  </div>
  <%= render partial: 'comments/form', locals: { comment: @comment, topic: @topic } %>
  <% if current_user.id == @topic.user_id %>
    <%= link_to '編集', edit_topic_path(@topic) %> |
  <% end %>
<%= link_to '戻る', topics_path %>