config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'

  root 'top#index'
  resources :topics do
    resources :comments
  end
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :users, only: [:index, :show]
  resources :relationships, only: [:create, :destroy]
  resources :conversations do
    resources :messages
  end
  if Rails.env.development?
   mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fbmodoki</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.pusher.com/3.2/pusher.min.js"></script>
    <% if user_signed_in? %>
    <script>
        var pusher = new Pusher('<%= ENV["PUSHER_KEY"] %>', {encrypted: true});

        var channel = pusher.subscribe("user_<%= current_user.id %>_channel");
        channel.bind('comment_created', function (data) {
            alert(data.message);
        });
        channel.bind('notification_created', function (data) {
            $('#unread_count').html(data.unread_counts);
        });
    </script>
    <% end %>
  </head>

  <body>
    <div class="modal-bg"></div><!--modal-bg-->
    <header class="header">
      <div class="header__inner">
        <div class="header_left">
          <h1 class="rootBtn">
              <%= link_to root_path do %>
                  <i class="fa fa-facebook-official" aria-hidden="true"></i>
              <% end %>
          </h1>
          <div class="head-search">
            <form class="search_box" id="SearchBox" method="get" action="/users" role="search">
              <input type="text" class="inputtext" maxlength="100" aria-label="検索" placeholder="友達を見つける" spellcheck="false">
              <button class="reDesignedBtn" type="submit" title="友達を見つける" aria-label="検索">
                <span class="accessible_elem">友達を見つける</span>
                <i class="fa fa-search" aria-hidden="true"></i>
              </button>
            </form>
          </div>
        </div>
        <div class="header_right">
          <div class="header-user">
            <% if user_signed_in? %>
              <%= link_to edit_user_registration_path do %>
                <%= profile_img(current_user)%>
                <%= current_user.name %>
              <% end %>
              </a>
            <% end %>
          </div>
        </div>
        <nav id="gnav" class="gnav">
          <ul>
            <button id="gnav-toggle-btn" class="gnav-toggle-btn">menu<span>&#x25BE;</span></button>
            <div id="gnav-toggle" class="gnav-popup toggle">
              <% if user_signed_in? %>
                <li><%= link_to 'フォロー', users_path %></li>
                <li><%= link_to "メッセージ", conversations_path %></li>
                <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to 'ログイン', new_user_session_path %></li>
                <li><%= link_to 'サインアップ', new_user_registration_path %></li>
              <% end %>
            </div>
            <li>
            <%= link_to  notifications_index_path, class: "navbar-brand" do %>
              <i class="fa fa-bell fa-1x">
                  <span id="unread_count"><%= @notifications_count %></span>
              </i>
            <% end %>
            </li>
          </ul>
        </nav>
      </div><!--header__inner-->
    </header>
    <section class="contents">
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-danger">
          <%= flash[:alert] %>
        </div>
      <% end %>

      <%= yield %>

      </section>
  </body>
</html>